# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prr < Formula
  desc "CLI tool that automates pull request review from a single command"
  homepage "https://github.com/richardthombs/prr"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/richardthombs/prr/releases/download/v0.4.0/prr_0.4.0_darwin_amd64.tar.gz"
      sha256 "fc8ca065dbcc4685755d86d5b67a6e5eeece53dcb0d29f512c376e2cd55bf135"

      define_method(:install) do
        bin.install "prr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/richardthombs/prr/releases/download/v0.4.0/prr_0.4.0_darwin_arm64.tar.gz"
      sha256 "1bcc28eb713b4bbc8c4e41462a7c5fa865dd5a69bb215d1f5c1c6cf73ad20f30"

      define_method(:install) do
        bin.install "prr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/richardthombs/prr/releases/download/v0.4.0/prr_0.4.0_linux_amd64.tar.gz"
      sha256 "2de8b33a66f8c69bc64efaad1da92d8350f1065e317109cc274dab68b5c74756"
      define_method(:install) do
        bin.install "prr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/richardthombs/prr/releases/download/v0.4.0/prr_0.4.0_linux_arm64.tar.gz"
      sha256 "baa92d133e5de4ed5d01f0a15928bdcb323a33ded63d526705e165976df04d18"
      define_method(:install) do
        bin.install "prr"
      end
    end
  end
end
